RCMD = R --vanilla
Sweave = $(RCMD) CMD Sweave
TEX2PDF = latexmk -pdf 

all: paper.pdf 

### Paper Targets ###
paper.pdf: paper/paper.tex \
					 vc.tex 
	cd paper && $(TEX2PDF) paper.tex
	cp paper/paper.pdf .

### Development Related Targets ####

# Lightweight version strings solution: http://thorehusfeldt.net/2011/05/13/including-git-revision-identifiers-in-latex/
vc.tex: .git/logs/HEAD
	echo "%%% This file is generated by Makefile." > vc.tex
	echo "%%% Do not edit this file!\n%%%" >> vc.tex
	git log -1 --format="format:\
		\\gdef\\GITAbrHash{%h}\
		\\gdef\\GITAuthorDate{%ad}\
		\\gdef\\GITAuthorName{%an}" >> vc.tex

clean:
	git clean -Xdf
